schema_version: '2.0'
directory_name: plots
description: Visual outputs from TinyCIMM-Polynomial experiment showing SCBF interpretability analysis of structured mathematical sequences through entropy dynamics, neural adaptation patterns, and comprehensive experimental visualization.
semantic_scope:
- polynomial_experiment_visualization
- scbf_interpretability_plots
- neural_adaptation_tracking
- entropy_dynamics_visualization
- mathematical_sequence_analysis
files:
- bifractal_evolution.png
- complete_dashboard.png
- entropy_collapse.png
- neural_growth.png
- predictions_vs_actual.png
- quantum_metrics_analysis.png
- training_dynamics.png
- weight_analysis.png
child_directories: []
