schema_version: 2.0
directory_name: recursive_entropy
description: >
  Explorations and models of recursive entropy in field theory, including code, notes, and results.
semantic_scope:
  - entropy
  - recursion
  - field theory
files: []
child_directories: []
