schema_versidescription: SCBF experimental session containing TinyCIMM-Prime deltas
  extended analysis with 100K iterations, demonstrating SCBF interpretability framework
  capabilities on large-scale prime number gap patterns with 6x performance improvement.
semantic_scope:
- '20250713_104841'
directory_name: '20250713_104841'
description: 'SCBF experiment run (timestamp: 20250713_104841) for symbolic collapse
  benchmarking and interpretability analysis.

  '
semantic_tags:
- scbf
- symbolic_collapse
- benchmarking
- interpretability
files: []
child_directories:
- tinycimm_prime_deltas_100000_20886596
