schema_version: 2.0
directory_name: docs
description: >
  Foundational documentation, theoretical papers, and supporting materials for Dawn Field Theory.
semantic_scope:
  - documentation
  - theory
files:
  - "[m][F][v1.0][C4][I5]_bifractal_time_emergence.md"
  - "[m][S][v1.0][C3][I4]_dawn_field_theory_timed_summary.md"
  - "[m][F][v1.0][C4][I5]_reality_as_herniation_precipitate.md"
  - "[m][F][v1.0][C4][I5]_superfluid_informational_crystallization.md"
  - "[m][F][v1.0][C4][I5]_herniation_hypothesis.md"
  - "[m][F][v2.0][C5][I5]_collapse_dynamics_in_entropic_fields.md"
  - "[m][F][v1.0][C4][I5]_dawn_field_theory_recursive_balance_field.md"
  - "[m][F][v1.0][C4][I5]_recursive_balance_field.md"
  - "[m][F][v1.0][C4][I5]_pi_harmonics.md"
  - "[m][F][v1.1][C4][I5]_recursive_entopy.md"
  - "[m][F][v1.0][C4][I4]_recursive_tree.md"
  - "[m][F][v1.0][C4][I4]_super_fluid.md"
child_directories:
  - docx
  - empirical_alignment
