schema_version: 2.0
directory_name: docs
description: 'Foundational documentation, theoretical papers, and supporting materials
  for Dawn Field Theory.

  '
semantic_scope:
- documentation
- theory
files:
- README.md
- '[id][F][v1.0][C5][I5][E]_landauer_erasure_cost_superfluidity_viscosity.md'
- '[id][F][v1.0][C5][I5][E]_phase_shifts_classical_vs_emergent_collapse.md'
- '[id][F][v1.0][C5][I5][E]_symbolic_collapse_recursive_field_pruning.md'
- '[id][F][v1.0][C5][I5][E]_symbolic_entropy_collapse_geometry_foundation.md'
- '[m][D][v0.9][C3][I3]_recursive_calculus_and_entropy_regulation.md'
- '[m][F][v0.1][C5][I5]_symbolic_entropy_collapse_and_hodge_mapping.md'
- '[m][F][v1.0][C4][I4]_recursive_tree.md'
- '[m][F][v1.0][C4][I4]_super_fluid.md'
- '[m][F][v1.0][C4][I5]_bifractal_time_emergence.md'
- '[m][F][v1.0][C4][I5]_dawn_field_theory_recursive_balance_field.md'
- '[m][F][v1.0][C4][I5]_herniation_hypothesis.md'
- '[m][F][v1.0][C4][I5]_pi_harmonics.md'
- '[m][F][v1.0][C4][I5]_reality_as_herniation_precipitate.md'
- '[m][F][v1.0][C4][I5]_recursive_balance_field.md'
- '[m][F][v1.0][C4][I5]_superfluid_informational_crystallization.md'
- '[m][F][v1.0][C5][I5][R]_recursive_symbol_collapse.md'
- '[m][F][v1.1][C4][I5]_recursive_entopy.md'
- '[m][F][v2.0][C5][I5]_collapse_dynamics_in_entropic_fields.md'
child_directories:
- docx
- empirical_alignment
