schema_version: '2.0'
directory_name: plots
description: Visual outputs from TinyCIMM-Harmonic experiment showing SCBF interpretability analysis of harmonic mathematical patterns through entropy dynamics, neural growth patterns, and comprehensive experimental dashboard.
semantic_scope:
- harmonic_experiment_visualization
- scbf_interpretability_plots
- neural_growth_tracking
- entropy_dynamics_visualization
- harmonic_pattern_analysis
files:
- bifractal_evolution.png
- complete_dashboard.png
- entropy_collapse.png
- neural_growth.png
- predictions_vs_actual.png
- quantum_metrics_analysis.png
- training_dynamics.png
- weight_analysis.png
child_directories: []
