schema_version: 2.0
directory_name: architecture
description: >
  Architecture documentation and supporting files for the GAIA model.
semantic_scope:
  - architecture
  - GAIA
files:
  - meta.yaml
child_directories:
  - modules
