schema_version: '2.0'
directory_name: freq_mod_sine
description: Metadata for freq_mod_sine experiment logs, including CSV metrics and logs.
semantic_scope:
- TinyCIMM-Planck
- experiment_logs
- freq_mod_sine
- metrics
- logs
files:
- TinyCIMM-Planck_freq_mod_sine_log.csv
- TinyCIMM-Planck_freq_mod_sine_metrics.csv
child_directories: []
