schema_version: 2.0
directory_name: reference_material
description: >
  Reference materials and supporting documents for balance-based energy generation blueprints. Includes datasets, papers, and technical notes.
semantic_scope:
  - reference
  - energy generation
  - blueprints
files:
- balance_based_energy_generationv1_2025-06-17 213826.png
- balance_based_energy_generationv2_2025-06-17 213826.png
- balance_based_energy_generationv2_2025-06-17 213826.txt
- carbon_energy_strategy_logs2025-06-17
- carbon_energy_strategy_logs2025-06-17 214113.png
child_directories: []
