schema_version: '2.0'
directory_name: experiment_results
description: Legacy experiment results storage - historical experimental data and outputs from SCBF framework development and testing phases.
semantic_scope:
- experiment_results
- legacy_results
- historical_data
- scbf_development
- testing_outputs
files: []
child_directories: []
