schema_version: "2.0"
directory_name: "docs"
description: >
  Documentation for the GAIA model, including theory, protocols, meta information, experiments, and architecture.
semantic_scope:
  - documentation
  - GAIA
files:
  - meta.yaml
child_directories:
  - theory
  - protocols
  - meta
  - experiments
  - architecture
