schema_version: 2.0
directory_name: optimization
description: >
  Optimization routines and supporting files for the CIMM core.
semantic_scope:
  - optimization
  - CIMM
files:
  - meta.yaml
child_directories:
  []
