schema_version: 2.0
directory_name: recursive_gravity
description: >
  Theoretical and computational work on recursive gravity models, including simulations and analytical results.
semantic_scope:
  - gravity
  - recursion
  - simulation
  - theory
files: []
child_directories: []
