schema_version: 2.0
directory_name: arithmetic
description: >
  Arithmetic theory, mappings, and supporting documents for Dawn Field Theory.
semantic_scope:
  - arithmetic
  - theory
files: []
child_directories:
  - hodge_mapping
