schema_version: 2.0
directory_name: compression
description: >
  Compression utilities and test scripts for Dawn Field Theory.
semantic_scope:
  - compression
  - devkit
files:
  - CompressionTest2.py
  - Compression_test1.py
  - EntropicCompression_test.py
  - compressiondoc.md
child_directories: []
