schema_version: '2.0'
directory_name: TinyCIMM
description: Core directory for the TinyCIMM model, including source code, goals, and experiment outputs for adaptive neural modeling and benchmarking.
semantic_scope:
- TinyCIMM
- model
- neural_network
- adaptive
- experiment
files:
- TinyCIMM_fractal_explainability.md
- goals.md
- tinycimm.py
child_directories:
- __pycache__
- experiment_images
- experiment_logs
- experiments
