schema_versdescription: SCBF experimental session containing TinyCIMM-Mathematical
  harmonic analysis with 10K iterations, demonstrating SCBF interpretability framework
  capabilities on harmonic mathematical patterns.
semantic_scope:
- '20250713_102425'
directory_name: '20250713_102425'
description: 'SCBF experiment run (timestamp: 20250713_102425) for symbolic collapse
  benchmarking and interpretability analysis.

  '
semantic_tags:
- scbf
- symbolic_collapse
- benchmarking
- interpretability
files: []
child_directories:
- tinycimm_mathematical_harmonic_10000_78fa6c71
