schema_version: 2.0
directory_name: utils
description: 'Utility scripts and supporting files for the CIMM model.

  '
semantic_scope:
- utils
- CIMM
files:
- __init__.py
- data_processing.py
- logging.py
child_directories: []
