schema_version: "2.0"
directory_name: "theory"
description: >
  Theoretical background and supporting documents for the GAIA model.
semantic_scope:
  - theory
  - GAIA
files:
  - meta.yaml
child_directories:
  []
