schema_version: 2.0
directory_name: learning
description: 'Learning algorithms and supporting files for the CIMM core.

  '
semantic_scope:
- learning
- CIMM
files:
- quantum_memory.py
- reinforcement_learning.py
- superfluid_dynamics.py
child_directories: []
