schema_version: 2.0
directory_name: foundational
description: 'Foundational theory, experiments, and documentation for Dawn Field Theory,
  including arithmetic, docs, experimental results, and a structured lexicon for both
  human and machine reference.

  '
semantic_scope:
- foundational
- theory
- experiment
- documentation
- lexicon
files:
- README.md
- lexicon.md
- lexicon.yaml
- whats_next.md
child_directories:
- arithmetic
- docs
- experiments
- legacy_docs_archive
