schema_version: 2.0
directory_name: architecture
description: >
  Architecture documents and protocols for cognition indexing in Dawn Field Theory.
semantic_scope:
  - architecture
  - cognition
files:
  - CIP_architecturev1.md
child_directories: []
