schema_version: '2.0'
directory_name: v1
description: 'Version 1 of the nuclear containment blueprint. Contains experimental
  archives, images, and reference materials for early-stage designs.

  '
semantic_scope:
- nuclear containment
- blueprints
- versioning
files:
- blueprint.md
- containment_math.md
- containment_theory.md
- containment_triptych_with_metrics.py
- results.md
child_directories:
- experimental_archive
- images
- reference_material
