schema_version: '2.0'
directory_name: tinycimm_prime_deltas_100000_20886596
description: Prime deltas experiment (100K steps) - Final loss 0.78 (6x improvement), validates hierarchical pattern discovery with multiple entropy collapse events and progressive network evolution.
semantic_scope:
- prime_deltas_extended
- 100000_steps
- hierarchical_discovery
- entropy_collapse_multiple
- network_evolution
- prime_validation
- breakthrough_experiment
files:
- checkpoint.json
- experiment_results.json
- experiment_summary.txt
child_directories:
- plots
