schema_versdescription: SCBF experimental session containing TinyCIMM-Polynomial sequence
  analysis with 10K iterations, demonstrating SCBF interpretability framework capabilities
  on structured mathematical sequences.
semantic_scope:
- '20250713_101847'
directory_name: '20250713_101847'
description: 'SCBF experiment run (timestamp: 20250713_101847) for symbolic collapse
  benchmarking and interpretability analysis.

  '
semantic_tags:
- scbf
- symbolic_collapse
- benchmarking
- interpretability
files: []
child_directories:
- tinycimm_polynomial_sequence_10000_47bfb087
