schema_versdescription: SCBF experimental session containing TinyCIMM-Recursive sequence
  analysis with 10K iterations, demonstrating SCBF interpretability framework capabilities
  on recursive mathematical patterns.
semantic_scope:
- '20250713_102144'
directory_name: '20250713_102144'
description: 'SCBF experiment run (timestamp: 20250713_102144) for symbolic collapse
  benchmarking and interpretability analysis.

  '
semantic_tags:
- scbf
- symbolic_collapse
- benchmarking
- interpretability
files: []
child_directories:
- tinycimm_recursive_sequence_10000_7fe3c68f
