schema_version: '2.0'
directory_name: hodge
description: >
  Hodge-related TODOs, notes, and planning for Dawn Field Theory.
directory_info: |
  This directory contains TODOs, notes, and planning documents related to Hodge theory and its applications within Dawn Field Theory. It serves as a workspace for organizing tasks and research directions specific to Hodge-related work.
semantic_scope:
- hodge
- planning
files:
- hodge_paper.md
- meta.yaml
child_directories: []
