schema_versdescription: SCBF experimental session containing TinyCIMM-Fibonacci ratios
  analysis with 10K iterations, demonstrating SCBF interpretability framework capabilities
  on mathematical golden ratio sequences.
semantic_scope:
- '20250713_101403'
directory_name: '20250713_101403'
description: 'SCBF experiment run (timestamp: 20250713_101403) for symbolic collapse
  benchmarking and interpretability analysis.

  '
semantic_tags:
- scbf
- symbolic_collapse
- benchmarking
- interpretability
files: []
child_directories:
- tinycimm_fibonacci_ratios_10000_9692c3a7
