openapi: 3.1.0
info:
  title: DawnField Repo Navigation API
  description: >
    Provides access to metadata and file contents from the Dawn Field Theory repository.
  version: v1.0.0
servers:
  - url: https://raw.githubusercontent.com/dawnfield-institute/dawn-field-theory/main

paths:
  /.cip/instructions_v2.0.yaml:
    get:
      operationId: GetCIPInstructions
      description: Retrieve the versioned CIP instructions file for meta.yaml v2.0 (dot-prefixed path).
      responses:
        '200':
          description: Successfully retrieved instructions_v2.0.yaml

  /{path}:
    get:
      operationId: GetFileContents
      description: >
        Fetch the contents of a specific file from the repository.
        
        You can search for files one at a time using the `path` parameter.
      parameters:
        - name: path
          in: path
          required: true
          description: Relative path to the file (e.g., models/core_model.py)
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved file contents

components:
  schemas: {}
