openapi: 3.1.0
info:
  title: DawnField Repo Navigation API
  description: Provides access to metadata and file contents from the Dawn Field Theory repository.
  version: v1.0.0

servers:
  - url: https://raw.githubusercontent.com/lornecodes/dawn-field-theory/main

paths:
  /cip/instructions_v2.0.yaml:
    get:
      operationId: GetCIPInstructions
      description: Retrieve the versioned CIP instructions file for meta.yaml v2.0.
      parameters: []
      responses:
        '200':
          description: Successfully retrieved instructions_v2.0.yaml

  /{path}:
    get:
      operationId: GetFileContents
      description: Fetch the contents of a specific file from the repository.
      parameters:
        - name: path
          in: path
          required: true
          description: Relative path to the file from the repo root (e.g., models/core_model.py)
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved file contents

  /batch:
    post:
      operationId: GetFileCluster
      description: Fetch the contents of multiple files or a cluster of files/directories in a single request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paths:
                  type: array
                  items:
                    type: string
                  description: List of relative paths to files or directories from the repo root (e.g., ["models/core_model.py", "foundational/experiments/"])
      responses:
        '200':
          description: Successfully retrieved file cluster

components:
  schemas: {}
