schema_version: 2.0
directory_name: entropy
description: 'Entropy-related modules and supporting files for the CIMM core.

  '
semantic_scope:
- entropy
- CIMM
files:
- __init__.py
- entropy_monitor.py
- quantum_potential_layer.py
child_directories: []
