schema_version: '2.0'
directory_name: tinycimm_fibonacci_ratios_10000_9692c3a7
description: Fibonacci ratios experiment (10K steps) - Final loss 3.18e-07, excellent convergence demonstrating clean entropy collapse and efficient pattern recognition.
semantic_scope:
- fibonacci_experiment
- 10000_steps
- excellent_convergence
- entropy_collapse
- pattern_recognition
- mathematical_sequence
- interpretability_validation
files:
- checkpoint.json
- experiment_results.json
- experiment_summary.txt
child_directories:
- plots
