schema_version: '2.0'
directory_name: docs
description: Metadata for TinyCIMM documentation, including fractal explainability and goals.
semantic_scope:
- TinyCIMM
- documentation
- fractal_explainability
- goals
files:
- TinyCIMM_fractal_explainability.md
- goals.md
child_directories: []
