schema_version: '2.0'
directory_name: chaotic_sine
description: Metadata for chaotic_sine experiment logs, including CSV metrics and logs.
semantic_scope:
- TinyCIMM
- experiment_logs
- chaotic_sine
- metrics
- logs
files:
- tinycimm_chaotic_sine_log.csv
- tinycimm_chaotic_sine_metrics.csv
child_directories: []
