schema_version: '2.0'
directory_name: AI_detection
description: Blueprint for an adaptive, feedback-driven AI detection module within the Dawn Field Theory framework.
  This module explores interpretable, entropy-aware neural architectures that dynamically grow and prune
  in response to feedback, aiming to address the blackbox problem in machine learning. Includes experiment
  protocols, metrics for transparency (entropy, fractal dimension), and integration points for further research
  on explainable and self-organizing AI
semantic_scope:
- AI_detection
files:
- '[cip][experiment][v1.0][2025-06-30]_dawn_field_recursive_fractal_entropy_provenance_pipeline.py'
- '[cip][protocol][v1.0][2025-06-30]_dawn_field_protocol_recursive_fractal_entropy_provenance.md'
child_directories: []
semantic_tags:
- ai-detection
- blueprint
- dawn-field-theory
- adaptive-ml
- explainable-ai
- feedback-driven
- experiment
- prototype
- entropy
- self-organizing
- neural-networks

