schema_version: 2.0
directory_name: legacy
description: 'Legacy and experimental compression scripts, documentation, and benchmarks
  for Dawn Field Theory.

  '
semantic_scope:
- compression
- legacy
- entropy
files:
- CompressionTest2.py
- Compression_test1.py
- EntropicCompression_test.py
- compressiondoc.md
child_directories: []
