schema_version: 2.0
directory_name: tools
description: >
  Utility scripts and tools for Dawn Field Theory, including format converters and automation helpers.
semantic_scope:
  - tools
  - utility
  - automation
files:
  - meta.yaml
  - converter.py
child_directories: []
