schema_version: '2.0'
directory_name: TinyCIMM-Planck
description: Metadata for TinyCIMM-Planck documentation, including fractal explainability
  and goals.
semantic_scope:
- TinyCIMM-Planck
- model
- neural_network
- adaptive
- experiment
files:
- '[id][F][v1.0][C4][I5][E]_symbolic_collapse_interpretability.md'
- output.txt
- report.md
- tinycimm_planck.py
child_directories:
- docs
- experiment_images
- experiment_logs
- experiments
