schema_versidescription: SCBF experimental session containing TinyCIMM-Prime deltas
  analysis with 10K iterations, demonstrating SCBF interpretability framework capabilities
  on prime number gap patterns.
semantic_scope:
- '20250713_102931'
directory_name: '20250713_102931'
description: 'SCBF experiment run (timestamp: 20250713_102931) for symbolic collapse
  benchmarking and interpretability analysis.

  '
semantic_tags:
- scbf
- symbolic_collapse
- benchmarking
- interpretability
files: []
child_directories:
- tinycimm_prime_deltas_10000_f1940154
