schema_version: '2.0'
directory_name: experiment_logs
description: Log files for TinyCIMM and MLP experiments, including loss, metrics, and benchmarking results for all signal types.
semantic_scope:
- experiment
- logs
- TinyCIMM
- MLP
- benchmarking
files:
- clean_sine_log.csv
- tinycimm_amp_mod_sine_log.csv
- tinycimm_chaotic_sine_log.csv
- tinycimm_clean_sine_log.csv
- tinycimm_freq_mod_sine_log.csv
- tinycimm_mlp_amp_mod_sine_log.csv
- tinycimm_mlp_chaotic_sine_log.csv
- tinycimm_mlp_clean_sine_log.csv
- tinycimm_mlp_freq_mod_sine_log.csv
- tinycimm_mlp_noisy_sine_log.csv
- tinycimm_noisy_sine_log.csv
child_directories: []
