schema_version: 2.0
directory_name: visualization
description: >
  Visualization tools and supporting files for the CIMM model.
semantic_scope:
  - visualization
  - CIMM
files:
  - meta.yaml
child_directories:
  []
