schema_version: '2.0'
directory_name: amp_mod_sine
description: Metadata for amp_mod_sine experiment logs, including CSV metrics and logs.
semantic_scope:
- TinyCIMM
- experiment_logs
- amp_mod_sine
- metrics
- logs
files:
- tinycimm_amp_mod_sine_log.csv
- tinycimm_amp_mod_sine_metrics.csv
child_directories: []
