schema_version: 2.0
directory_name: symbolic_bifractal
description: >
  Symbolic bifractal analysis, including code, notes, and results for bifractal structures in symbolic systems.
semantic_scope:
  - bifractal
  - symbolic
  - analysis
  - mathematics
files: []
child_directories: []
