name: Update map.yaml

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  update-map-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run generate_path.py
        run: python tools/generate_path.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add map.yaml
          git diff --cached --quiet || git commit -m "Auto-update map.yaml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
