schema_version: '2.0'
directory_name: loggers
description: SCBF experiment logging infrastructure - handles real-time data collection, experiment tracking, and result serialization for interpretability analysis.
semantic_scope:
- loggers
- experiment_logging
- data_collection
- real_time_tracking
- result_serialization
- scbf_monitoring
files:
- __init__.py
- experiment_logger.py
child_directories:
- __pycache__
