schema_version: 2.0
directory_name: models
description: 'Model implementations and supporting code for Dawn Field Theory, including
  CIMM and GAIA frameworks.

  '
semantic_scope:
- models
- CIMM
- GAIA
files:
- README.md
child_directories:
- CIMM
- GAIA
- TinyCIMM
- scbf
