schema_version: '2.0'
directory_name: plots
description: Visual outputs from TinyCIMM-Recursive experiment showing SCBF interpretability
  analysis of recursive mathematical patterns through bifractal evolution tracking,
  entropy collapse detection, and neural adaptation visualization.
semantic_scope:
- recursive_experiment_visualization
- scbf_interpretability_plots
- neural_adaptation_tracking
- entropy_dynamics_visualization
- recursive_pattern_analysis
files:
- bifractal_evolution.png
- complete_dashboard.png
- entropy_collapse.png
- neural_growth.png
- predictions_vs_actual.png
- quantum_metrics_analysis.png
- training_dynamics.png
- weight_analysis.png
child_directories: []
